name: aatrnaseqpipe

channels:
  - conda-forge
  - bioconda

dependencies:
  - pysam
  - numpy
  - pandas
  - samtools >= 1.12
  - bwa
  - deeptools
  - snakemake
  - pulp >=2.0,<2.8.0 
  - pip
  - pip:
    - pod5

