name: aatrnaseq

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - pysam
  - numpy
  - pandas
  - samtools >= 1.12
  - bwa
  - deeptools
  - snakemake
  - scikit-learn
  - matplotlib

