name: aatrnaseqpipe

channels:
  - conda-forge
  - bioconda

dependencies:
  - pysam
  - numpy
  - pandas
  - samtools >= 1.12
  - bwa
  - deeptools
  - snakemake
  - pulp >=2.0,<2.8.0 
  - gitpython 
  - pip
  - pip:
    - pod5
    - git+https://github.com/rnabioco/remora.git@metrics_missing_ok
