executor: cluster-generic
cluster-generic-submit-cmd:
  bsub
    -o "{log}.out"
    -e "{log}.err"
    -J "{rule}-{wildcards}"
    -R "select[mem>{resources.mem_mb}] rusage[mem={resources.mem_mb}] span[hosts=1]"
    -n {threads}
    -q "{resources.queue}" 
    "{resources.gpu_opts}"

# note that GB values should be passed to mem_mb
default-resources:
  - mem_mb=8
  - queue="rna"
  - gpu_opts=""

jobs: 50 

# the cluster only has 1 gpu node
# setting this to 1 makes snakemake only schedule 1 gpu job at a time
resources: 
  - ngpu=1

# set rule specific requirements
set-resources:
  - rebasecall:queue="gpu"
  - rebasecall:gpu_opts="-gpu num=1:j_exclusive=yes"
  - rebasecall:ngpu=1
  - rebasecall:mem_mb=24
  - remora:mem_mb=24
    

printshellcmds: True
show-failed-logs: True
latency-wait: 60
cluster-generic-cancel-cmd: "bkill"
